### ISSUE TITLE
トップページ一番下のdocsへのリンクが正しくない

### ISSUE THREAD

**Issue by InuInu2022** [ymmehub/ymmehub.github.io#4]
https://ymme.f5.si/

![image](https://github.com/user-attachments/assets/40bcd475-07e3-43c8-a590-ec333150b715)

トップページ一番下のdocsへのリンク(「ドキュメント」)が正しくないようです。

- 誤：`https://ymme.f5.si/docs/`
- 正：`https://docs.ymme.f5.si/`

**Comment by RainKasa** [comment]
修正しました。
